GammaClient/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GammaClient.Services;
using GammaClient.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GammaClient.Controllers
{
    public class PrincipalController : Controller
    {
        private readonly SchoolClient _schoolClient;

        public PrincipalController(SchoolClient schoolClient)
        {
            _schoolClient = schoolClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SendSearchValue(string value)
        {
            var schools = await _schoolClient.GetAllSchools();
            List<SchoolVM> schoolsbyFilter = new List<SchoolVM>();
            foreach (var school in schools)
            {
                if (school.Name.ToLower().Contains(value.ToLower()))
                {
                    schoolsbyFilter.Add(school);
                }
            }

            return PartialView(schoolsbyFilter);
        }

        [HttpGet]
        public async Task<IActionResult> SchoolDetails(string id)
        {
            var schools = await _schoolClient.GetAllSchools();
            SchoolVM school = schools.SingleOrDefault(s => s.Id == id);
            return PartialView(school);

        }

        [HttpGet]
        public IActionResult AddSchool()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddSchool([FromForm] SchoolVM newSchool)
        {
            var result = await _schoolClient.AddSchool(newSchool);
            if (result.Status == Status.Error)
            {
                TempData["addSchoolErrorMessage"] = result.Message;
                return RedirectToAction("AddSchool");
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> ShowTeachers(string schoolid)
        {
            var teachers = await _schoolClient.GetAllTeachers();

            var schoolTeachers = teachers.Where(t => t.SchoolId == schoolid);

            var schools = await _schoolClient.GetAllSchools();
            var school = schools.FirstOrDefault(s => s.Id == schoolid);

            ViewBag.showTeachersSchool = school.Name;
            ViewBag.schoolId = schoolid;
            return View(schoolTeachers);
        }

        public async Task<IActionResult> ShowStudents(string schoolid)
        {
            var students = await _schoolClient.GetAllStudents();

            var schoolStudents = students.Where(s => s.SchoolId == schoolid);

            var schools = await _schoolClient.GetAllSchools();
            var school = schools.FirstOrDefault(s => s.Id == schoolid);

            ViewBag.showStudentsSchool = school.Name;
            ViewBag.schoolId = schoolid;
            return View(schoolStudents);
        }

        [HttpGet]
        public async Task<IActionResult> AddTeachers(string schoolid)
        {
            var teachers = await _schoolClient.GetAllTeachers();

            List<TeacherVM> teachersWithoutSchool = new List<TeacherVM>();
            foreach (var teacher in teachers)
            {
                if (teacher.SchoolId == null)
                {
                    teachersWithoutSchool.Add(new TeacherVM
                    {
                        MemberId = teacher.MemberId,
                        FirstName = teacher.FirstName,
                        LastName = teacher.LastName
                    });
                }
            }

            var schools = await _schoolClient.GetAllSchools();
            var school = schools.FirstOrDefault(s => s.Id == schoolid);

            ViewBag.showTeachersSchool = school.Name;
            ViewBag.schoolId = schoolid;
            return View(teachersWithoutSchool);
        }

        [HttpPost]
        public async Task<IActionResult> AddTeachers(List<TeacherVM> model, string schoolId)
        {
            List<TeacherVM> selectedTeachers = new List<TeacherVM>();

            foreach(var teacher in model)
            {
                if (teacher.IsSelected)
                {
                    teacher.SchoolId = schoolId;
                    selectedTeachers.Add(teacher);
                }
            }

            var result = await _schoolClient.AddTeachers(selectedTeachers);

            if(result.Status == Status.Error)
            {
                TempData["addTeachersErrorMessage"] = result.Message;
                return RedirectToAction("AddTeachers", new { schoolId });
            }

            return RedirectToAction("ShowTeachers", new { schoolId });
        }

        [HttpGet]
        public async Task<IActionResult> AddStudents(string schoolid)
        {
            var students = await _schoolClient.GetAllStudents();

            List<StudentVM> studentsWithoutSchool = new List<StudentVM>();
            foreach (var student in students)
            {
                if (student.SchoolId == null)
                {
                    studentsWithoutSchool.Add(new StudentVM
                    {
                        MemberId = student.MemberId,
                        FirstName = student.FirstName,
                        LastName = student.LastName
                    });
                }
            }

            var schools = await _schoolClient.GetAllSchools();
            var school = schools.FirstOrDefault(s => s.Id == schoolid);

            ViewBag.showStudentsSchool = school.Name;
            ViewBag.schoolId = schoolid;
            return View(studentsWithoutSchool);
        }

        [HttpPost]
        public async Task<IActionResult> AddStudents(List<StudentVM> model, string schoolId)
        {
            List<StudentVM> selectedStudents = new List<StudentVM>();

            foreach (var student in model)
            {
                if (student.IsSelected)
                {
                    student.SchoolId = schoolId;
                    selectedStudents.Add(student);
                }
            }

            var result = await _schoolClient.AddStudents(selectedStudents);

            if (result.Status == Status.Error)
            {
                TempData["addStudentsErrorMessage"] = result.Message;
                return RedirectToAction("AddStudents", new { schoolId });
            }

            return RedirectToAction("ShowStudents", new { schoolId });
        }
    
        [HttpGet]
        public async Task<IActionResult> EditTeacher(string teacherid, string schoolid)
        {
            var teachers = await _schoolClient.GetAllTeachers();
            var selectedTeacher = teachers.FirstOrDefault(t => t.MemberId == teacherid);
        
            if(selectedTeacher != null)
            {
                List<SchoolVM> schools = await _schoolClient.GetAllSchools();
                var school = schools.FirstOrDefault(s => s.Id == schoolid);
                ViewBag.showTeachersSchool = school.Name;
                return View(selectedTeacher);
            }

            return RedirectToAction("ShowTeachers", new { schoolid });
        }

        [HttpPost]
        public async Task<IActionResult> EditTeacher(TeacherVM teacherVM)
        {
            var result = await _schoolClient.UpdateTeacher(teacherVM);

            if(result.Status == Status.Error)
            {
                ViewBag["updateTeacherErrorMessage"] = result.Message;
                return RedirectToAction("EditTeacher", new { teacherid = teacherVM.MemberId, schoolid = teacherVM.SchoolId });
            }

            return RedirectToAction("ShowTeachers", new { schoolid = teacherVM.SchoolId });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveTeacher(string teacherid, string school)
        {
            var result = await _schoolClient.RemoveTeacher(teacherid);

            if (result.Status == Status.Error)
            {
                ViewData["removeTeacherErrorMessage"] = result.Message;
            }
            
            return RedirectToAction("ShowTeachers", new { schoolid = school });
        }

        [HttpGet]
        public async Task<IActionResult> EditStudent(string studentid, string schoolid)
        {
            var students = await _schoolClient.GetAllStudents();
            var selectedStudent = students.FirstOrDefault(t => t.MemberId == studentid);

            if (selectedStudent != null)
            {
                List<SchoolVM> schools = await _schoolClient.GetAllSchools();
                var school = schools.FirstOrDefault(s => s.Id == schoolid);
                ViewBag.showTeachersSchool = school.Name;
                return View(selectedStudent);
            }

            return RedirectToAction("ShowStudents", new { schoolid });
        }

        [HttpPost]
        public async Task<IActionResult> EditStudent(StudentVM studentVM)
        {
            var result = await _schoolClient.UpdateStudent(studentVM);

            if (result.Status == Status.Error)
            {
                ViewBag["updateStudentErrorMessage"] = result.Message;
                return RedirectToAction("EditStudent", new { studentid = studentVM.MemberId, schoolid = studentVM.SchoolId });
            }

            return RedirectToAction("ShowStudents", new { schoolid = studentVM.SchoolId });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveStudent(string studentid, string school)
        {
            var result = await _schoolClient.RemoveStudent(studentid);

            if (result.Status == Status.Error)
            {
                ViewData["removeStudentErrorMessage"] = result.Message;
            }

            return RedirectToAction("ShowStudents", new { schoolid = school });
        }
    }
}

GammaClient/Views/Principal/AddSchool.cshtml
@model GammaClient.ViewModels.SchoolVM
@inject GammaClient.Services.MemberClient _memberClient;

@{
    ViewData["Title"] = "Adaugă Instituție";
    var member = await _memberClient.GetCurrentClient();
}

<div class="container-fluid bg-primary text-light pt-3 pb-4">
    <div class="container">
        <h2 class="text-white">Adaugă o instituție de învățământ</h2>
    </div>
</div>
<div class="container mt-3 pb-3">
    <div class="row text-primary">
        <div class="col-md-4">
            <form asp-action="AddSchool">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control border-primary" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Type" class="control-label"></label>
                    <input asp-for="Type" class="form-control border-primary" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control border-primary" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control border-primary" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mail" class="control-label"></label>
                    <input asp-for="Mail" class="form-control border-primary" />
                    <span asp-validation-for="Mail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Creează" class="btn btn-outline-primary" />
                </div>
            </form>
        </div>
    </div>
    <p class="error-message">@TempData["addSchoolErrorMessage"]</p>
    <div>
        <a asp-action="Index" class="text-primary">Înapoi la pagina principală</a>
    </div>
</div>


@section Scripts {
    <script src="~/js/removeNavbarCollapse.js"></script>
    <script src="~/js/colorPrincipalPage.js"></script>
    @if (member != null)
    {
        <script>
        popi = document.getElementById("popi");
        popi.title = '<span class="text-center d-block">@member.UserName</span>';
        popi.setAttribute("data-content",
            '<!DOCTYPE html><html><p class="text-center">@member.FirstName @member.LastName</p>' +
            '<a href="../Account/Logout" class="btn btn-dark text-light">Deconectare</a></html>');
        </script>
    }
    else
    {
        <script>
            location.href = "../Account/Login";
        </script>
    }
}

GammaClient/Views/Principal/AddStudents.cshtml
@model List<GammaClient.ViewModels.StudentVM>
@inject GammaClient.Services.MemberClient _memberClient;

@{
    ViewData["Title"] = "Adaugă Studenți";
    var schoolName = ViewBag.showStudentsSchool;
    var schoolId = ViewBag.schoolId;
    var member = await _memberClient.GetCurrentClient();
}

<div class="container-fluid bg-primary text-light pt-3 pb-4">
    <div class="container">
        <h2 class="text-white">@schoolName</h2>
        <hr class="border-light" />
        <h5 class="text-white">Adaugați studenți în catalogul instituției</h5>
    </div>
</div>

<div class="container mt-3 pb-3">
    @if (Model.Any())
    {
        <form method="post" asp-action="AddStudents">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-4">
                    <div class="d-flex flex-column align-items-start">
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <div class="custom-control custom-checkbox d-inline">
                                <input type="hidden" asp-for="@Model[i].FirstName" />
                                <input type="hidden" asp-for="@Model[i].LastName" />
                                <input type="hidden" asp-for="@Model[i].MemberId" />
                                <input type="checkbox" class="custom-control-input" asp-for="@Model[i].IsSelected" />
                                <label class="custom-control-label text-primary" asp-for="@Model[i].IsSelected">
                                    @Model[i].FirstName @Model[i].LastName
                                </label>
                            </div>
                        }
                    </div>
                    <input type="hidden" asp-for="@schoolId" />
                    <div class="form-group mt-5">
                        <input type="submit" value="Salvează modificările" class="btn btn-outline-primary" />
                    </div>

                    <div>
                        <p class="error-message">@TempData["addStudentsErrorMessage"]</p>
                    </div>
                </div>
            </div>
        </form>
    }
    else
    {
        <p class="text-primary">Nu mai există studenți înscriși</p>
    }
    <div>
        <a class="btn btn-outline-primary mt-auto" asp-action="ShowStudents" asp-route-schoolid="@schoolId">Înapoi la lista de studenți</a>
    </div>
</div>

@section Scripts {
    <script src="~/js/removeNavbarCollapse.js"></script>
    <script src="~/js/colorPrincipalPage.js"></script>
    @if (member != null)
    {
        <script>
        popi = document.getElementById("popi");
        popi.title = '<span class="text-center d-block">@member.UserName</span>';
        popi.setAttribute("data-content",
            '<!DOCTYPE html><html><p class="text-center">@member.FirstName @member.LastName</p>' +
            '<a href="../Account/Logout" class="btn btn-dark text-light">Deconectare</a></html>');
        </script>
    }
    else
    {
        <script>
            location.href = "../Account/Login";
        </script>
    }
}

GammaClient/Views/Principal/AddTeachers.cshtml
@model List<GammaClient.ViewModels.TeacherVM>
@inject GammaClient.Services.MemberClient _memberClient;

@{
    ViewData["Title"] = "Adaugă Profesori";
    var schoolName = ViewBag.showTeachersSchool;
    var schoolId = ViewBag.schoolId;
    var member = await _memberClient.GetCurrentClient();
}

<div class="container-fluid bg-primary text-light pt-3 pb-4">
    <div class="container">
        <h2 class="text-white">@schoolName</h2>
        <hr class="border-light" />
        <h5 class="text-white">Adaugați profesori în personalul instituției</h5>
    </div>
</div>

<div class="container mt-3 pb-3">
    @if (Model.Any())
    {
        <form method="post" asp-action="AddTeachers">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-4">
                    <div class="d-flex flex-column align-items-start">
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <div class="custom-control custom-checkbox d-inline">
                                <input type="hidden" asp-for="@Model[i].FirstName" />
                                <input type="hidden" asp-for="@Model[i].LastName" />
                                <input type="hidden" asp-for="@Model[i].MemberId" />
                                <input type="checkbox" class="custom-control-input" asp-for="@Model[i].IsSelected" />
                                <label class="custom-control-label text-primary" asp-for="@Model[i].IsSelected">
                                    @Model[i].FirstName @Model[i].LastName
                                </label>
                            </div>
                        }
                    </div>
                    <input type="hidden" asp-for="@schoolId" />
                    <div class="form-group mt-5">
                        <input type="submit" value="Salvează modificările" class="btn btn-outline-primary" />
                    </div>

                    <div>
                        <p class="text-primary">@TempData["addTeachersErrorMessage"]</p>
                    </div>
                </div>
            </div>
        </form>
    }
    else
    {
        <p class="text-primary">Nu există profesori disponibili</p>
    }
    <div>
        <a class="mt-auto" asp-action="ShowTeachers" asp-route-schoolid="@schoolId">Înapoi la lista de profesori</a>
    </div>
</div>

@section Scripts {
    <script src="~/js/removeNavbarCollapse.js"></script>
    <script src="~/js/colorPrincipalPage.js"></script>
    @if (member != null)
    {
        <script>
        popi = document.getElementById("popi");
        popi.title = '<span class="text-center d-block">@member.UserName</span>';
        popi.setAttribute("data-content",
            '<!DOCTYPE html><html><p class="text-center">@member.FirstName @member.LastName</p>' +
            '<a href="../Account/Logout" class="btn btn-dark text-light">Deconectare</a></html>');
        </script>
    }
    else
    {
        <script>
            location.href = "../Account/Login";
        </script>
    }
}

GammaClient/Views/Principal/SchoolDetails.cshtml
@model GammaClient.ViewModels.SchoolVM

@{
    ViewData["Title"] = "Detalii";
}

<div class="w3-animate-opacity">
    <h4>@Model.Name</h4>
    <hr />
    <p>@Model.Address</p>
    <br />
    <p>@Model.Mail</p>
    <p>@Model.Phone</p>

    <a class="d-block" asp-action="ShowTeachers" asp-route-schoolid="@Model.Id">Vezi profesorii</a>
    <a class="d-block" asp-action="ShowStudents" asp-route-schoolid="@Model.Id">Vezi studenții</a>
</div>

GammaClient/Views/Principal/SendSearchValue.cshtml
@model IEnumerable<GammaClient.ViewModels.SchoolVM>
@{
    ViewData["Title"] = "Rezultatele căutării";
}

@if (Model.Any())
{
    foreach (var school in Model)
    {  
        <div class="search-school-result w3-animate-opacity" onclick="showDetail('@school.Id')">
            <div class="p-2">
                <h5>@school.Name</h5>
                <p>@school.Type</p>
            </div>
            <hr />
        </div>

    }

}
else
{
    <h5>Nu există rezultate</h5>
}

<script>
    function showDetail(value) {
        $.get("/Principal/SchoolDetails", { id: value })
            .done(function (response) {
                $("#detailsSearchResult").html(response);
            });
    }
</script>

GammaClient/Views/Principal/ShowStudents.cshtml
@model IEnumerable<GammaClient.ViewModels.StudentVM>
@inject GammaClient.Services.MemberClient _memberClient;

@{
    ViewData["Title"] = "Studenți";
    var schoolName = ViewBag.showStudentsSchool;
    var schoolId = ViewBag.schoolId;
    var member = await _memberClient.GetCurrentClient();
}


<div class="container-fluid bg-primary text-light pt-3 pb-4">
    <div class="container">
        <h2 class="text-white">@schoolName</h2>
        <hr class="border-white"/>
        <h4 class="text-white">Studenți</h4>
    </div>
</div>
<div class="container mt-3 pb-3">
    @if (Model.Any())
    {
        <div class="table-responsive-sm">
            <table class="table text-primary border-primary">
                <thead>
                    <tr>
                        <th>
                            Student
                        </th>
                        <th>
                            Clasa
                        </th>
                        <th>
                            Specializare
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-primary">
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Grade)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FieldOfStudy)
                            </td>
                            <td>
                                <a class="text-primary" asp-action="EditStudent" asp-controller="Principal" asp-route-studentid="@item.MemberId" asp-route-schoolid="@schoolId">Editează</a>
                            </td>
                            <td>
                                <a href="#" class="text-primary" onclick="deleteInfoStudent('@item.FirstName @item.LastName', '@item.MemberId', '@item.SchoolId');">
                                    Șterge
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        

        <div id="myModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="deletedElement"></h3>
                    <span class="close">&times;</span>
                </div>
                <div class="modal-body">
                    <p>Confirmați finalizarea operației</p>
                </div>
                <div class="modal-footer">
                    <input id="studentid" type="hidden" />
                    <input id="schoolid" type="hidden" />
                    <button onclick="routeStudent();" class="btn btn-primary">Ok</button>
                    <button id="giveUp" class="btn btn-primary">Renunță</button>
                </div>
            </div>
        </div>
    }
    else
    {
        <hr class="border-primary" />
        <p class="text-primary">Nu există studenți înregistrați pentru această instituție</p>
    }

    <a asp-action="AddStudents" class="btn btn-outline-primary" asp-route-schoolid="@schoolId">Adaugă studenți</a>
    <br />
    <br />
    <a asp-action="Index" class="text-primary">Întoarce-te la pagina principală</a>
</div>

@section Scripts {
    <script src="~/js/removeNavbarCollapse.js"></script>
    <script src="~/js/colorPrincipalPage.js"></script>
    <script src="~/js/modal.js"></script>
    <script>
        function deleteInfoStudent(name, student, school) {
            deletedElement.innerHTML = "Stergeți " + name;
            modal.style.display = "block";
            document.getElementById("studentid").value = student;
            document.getElementById("schoolid").value = school;
        }

        function routeStudent() {
            let studentid = document.getElementById("studentid").value;
            let schoolid = document.getElementById("schoolid").value;

            let link = document.createElement("a");
            link.setAttribute("href", "/Principal/RemoveStudent?studentid=" + studentid + "&school=" + schoolid);
            link.click();
        }
    </script>

    @if (member != null)
    {
        <script>
        popi = document.getElementById("popi");
        popi.title = '<span class="text-center d-block">@member.UserName</span>';
        popi.setAttribute("data-content",
            '<!DOCTYPE html><html><p class="text-center">@member.FirstName @member.LastName</p>' +
            '<a href="../Account/Logout" class="btn btn-dark text-light">Deconectare</a></html>');
        </script>
    }
    else
    {
        <script>
            location.href = "../Account/Login";
        </script>
    }
}

GammaClient/Views/Principal/ShowTeachers.cshtml
@model IEnumerable<GammaClient.ViewModels.TeacherVM>
@inject GammaClient.Services.MemberClient _memberClient;

@{
    ViewData["Title"] = "Profesori";
    var schoolName = ViewBag.showTeachersSchool;
    var schoolId = ViewBag.schoolId;
    var member = await _memberClient.GetCurrentClient();
}


<div class="container-fluid bg-primary text-light pt-3 pb-4">
    <div class="container">
        <h2 class="text-white">@schoolName</h2>
        <hr class="border-white"/>
        <h4 class="text-white">Cadre didactice</h4>
    </div>
</div>
<div class="container mt-3 pb-3">
    @if (Model.Any())
    {
        <div class="table-responsive-sm">
            <table class="table text-primary border-primary">
                <thead>
                    <tr>
                        <th>
                            Profesor
                        </th>
                        <th>
                            Departament
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-primary">
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Department)
                            </td>
                            <td>
                                <a class="text-primary" asp-action="EditTeacher" asp-controller="Principal" asp-route-teacherid="@item.MemberId" asp-route-schoolid="@schoolId">Editează</a>
                            </td>
                            <td>
                                <a href="#" class="text-primary" onclick="deleteInfo('@item.FirstName @item.LastName', '@item.MemberId', '@item.SchoolId');">
                                    Șterge
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        
        <br/>
        <p class="error-message-light">@ViewData["removeTeacherErrorMessage"]</p>

        <div id="myModal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="deletedElement"></h3>
                    <span class="close">&times;</span>
                </div>
                <div class="modal-body">
                    <p>Confirmați finalizarea operației</p>
                </div>
                <div class="modal-footer">
                    <input id="teacherid" type="hidden" />
                    <input id="schoolid" type="hidden" />
                    <button onclick="route();" class="btn btn-primary">Ok</button>
                    <button id="giveUp" class="btn btn-primary">Renunță</button>
                </div>
            </div>
        </div>

    }
    else
    {
        <hr style="border-color:aliceblue;" />
        <p class="text-primary">Nu există profesori înregistrați pentru această instituție</p>
    }

    <a asp-action="AddTeachers" class="btn btn-outline-primary" asp-route-schoolid="@schoolId">Adaugă profesori</a>
    <br />
    <br />
    <a asp-action="Index" class="text-primary">Întoarce-te la pagina principală</a>
</div>

@section Scripts {
    <script src="~/js/removeNavbarCollapse.js"></script>
    <script src="~/js/colorPrincipalPage.js"></script>
    <script src="~/js/modal.js"></script>
    <script>
        function deleteInfo(name, teacher, school)
        {
            deletedElement.innerHTML = "Stergeți " + name;
            modal.style.display = "block";
            document.getElementById("teacherid").value = teacher;
            document.getElementById("schoolid").value = school;
        }

        function route() {
            let teacherid = document.getElementById("teacherid").value;
            let schoolid = document.getElementById("schoolid").value;

            let link = document.createElement("a");
            link.setAttribute("href", "/Principal/RemoveTeacher?teacherid=" + teacherid + "&school=" + schoolid);
            link.click();
        }
    </script>
    @if (member != null)
    {
        <script>
        popi = document.getElementById("popi");
        popi.title = '<span class="text-center d-block">@member.UserName</span>';
        popi.setAttribute("data-content",
            '<!DOCTYPE html><html><p class="text-center">@member.FirstName @member.LastName</p>' +
            '<a href="../Account/Logout" class="btn btn-dark text-light">Deconectare</a></html>');
        </script>
    }
    else
    {
        <script>
            location.href = "../Account/Login";
        </script>
    }

}